// <auto-generated/>
using System.Reflection;

[assembly: AssemblyProductAttribute("Rothko")]
[assembly: AssemblyVersionAttribute("0.0.3")]
[assembly: AssemblyFileVersionAttribute("0.0.3")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.0.3";
    }
}
